name: Matrix Demo
on: push
jobs:
  build:
    stratrgy:
      matrix:
        node-version: [12, 14, 15]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
